name: chikin_nft_canvas_client
description: Dart client for Chikin Nft Canvas (solana)
version: 0.0.1
homepage: chikin.run
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  solana:
    git:
      url: https://github.com/ChikinDeveloper/ext_solana_dart
      path: packages/solana
      ref: ae03e3929f39bd849198421647166b9adc1950fc

  solana_js:
    git:
      url: https://github.com/ChikinDeveloper/dart_solana_js
      ref: b0ca11d7008e442cf8eb4c6e82c9f2eb8926aa9d

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0