name: chikin_nft_canvas_client
description: Dart client for Chikin Nft Canvas (solana)
version: 0.0.1
homepage: chikin.run
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #
  solana:
    git: https://github.com/ChikinDeveloper/dart-solana-lib

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0